version: '3'
services:
  discovery:
    container_name: discovery-server
    build:
      context: discovery
    image: discovery-server:latest
    ports:
      - "8761:8761"
  fact-service:
    container_name: fact-server
    build:
      context: fact-service
    image: fact-server:latest
    environment:
      DISCOVERY_HOST: discovery
    restart: on-failure
    depends_on:
      - discovery
  #      - config
    ports:
      - "8081:8081"
  weather-service:
    container_name: weather-server
    build:
      context: weather-service
    image: weather-server:latest
    environment:
      DISCOVERY_HOST: discovery
    restart: on-failure
    depends_on:
      - discovery
    #      - config
    ports:
      - "8082:8082"