weather:
  api:
    url: https://api.api-ninjas.com/v1/weather
    key: 8jRa9jJLclIRRO4eMV7jCA==Qdkn8TTOe9m1eo44

spring:
  application:
    name: weather-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka