eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: information-service

server:
  port: 8080